spring:
  application:
    name: eureka-server
  zipkin:
    base-url: http://zipkin:9411
  sleuth:
    integration:
      enabled: true
server:
  port: 8761
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    prefer-ip-address: true