eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery:8761/eureka
  instance:
    prefer-ip-address: true

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: one
          uri: http://one:8082
          predicates:
            - Path=/api/movies/**
        - id: two
          uri: http://two:8083
          predicates:
            - Path=/api/reviews/**
  zipkin:
    base-url: http://zipkin:9411
  sleuth:
    integration:
      enabled: true
server:
  port: 8765